name: Create AWS Infra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pulumi pulumi-aws

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Pulumi login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }} 
      run: |
        source venv/bin/activate
        pulumi login

    - name: Pulumi stack select
      run: |
        source venv/bin/activate
        cd infra
        pulumi stack select arifhossaincse22/infra/k3s_in_AWS

    - name: Pulumi up
      run: |
        source venv/bin/activate
        cd infra
        pulumi up --yes
